### ISSUE TITLE
storage.py _cleanup TypeError: unsupported operand type(s) for -: 'str' and 'int'

### ISSUE THREAD

**Issue by 1letter** [plone/plone.scale#12]
Hi, i get an error while rendering an template with Images. I use Plone 4.3.9. Please no irritations because of the path in the traceback.
```txt
  File "/opt/Plone-4.3.3/buildout-cache/eggs/plone.scale-1.4.1-py2.7.egg/plone/scale/storage.py", line 166, in scale
    self._cleanup()
  File "/opt/Plone-4.3.3/buildout-cache/eggs/plone.scale-1.4.1-py2.7.egg/plone/scale/storage.py", line 190, in _cleanup
    value['modified'] < modified_time - KEEP_SCALE_MILLIS):
TypeError: unsupported operand type(s) for -: 'str' and 'int'

# Here my Debug Output of the Values:
2016-08-27 18:58:05 INFO plone.scale key: d7620496-5e61-4f6b-8490-b30399d809ba
2016-08-27 18:58:05 INFO plone.scale modified time     1467291549.8024411467291549.8028791467291549.8032841467291549.8036901467291549.804092
2016-08-27 18:58:05 INFO plone.scale value['modified'] 1467291549.8024411467291549.8028791467291549.8032841467291549.8036901467291549.804092
```
I think it's not an Integer, all values are 'str'. The comparison but needs integer values . What should i do? Should I overwrite the _cleanup Method and purge the Storage every time?

**Comment by mauritsvanrees** [comment]
Both 'modified' values should be integers or floats. It is the same as what you get when you run `context.modified()` or the same type as when running `time.time()`.

Is this with the standard Image content type of Plone?  Or a different one from own code or an add-on? Maybe you have code that overrides the `modified` method to do something weird.

The two values you pasted above are the same. What is strange, is that they start with `1467291549.802441` followed by the same value a couple of times, except for the part after the dot.

You could check `isinstance(modified_time, (float, int))`. If that is False, then there is no sense in subtracting a value. Same for `value['modified']`. I guess in that case it is best to simply compare the two values and delete the scale if they are different.

**Comment by idgserpro** [comment]
Funny, I just got this error in an old Plone 4.3.3 installation and plone.scale 1.3.3.

We were having the same issue as https://github.com/plone/plone.scale/pull/3/files#r10500627, then after seeing https://github.com/plone/plone.scale/pull/4/files we decided to upgrade just plone.scale to 1.3.4 (since we can't do a full upgrade on this specific instance).

But then we're getting the same problem as this issue when trying to replace an image to a new one: we get the same traceback

```
Module plone.scale.storage, line 73, in scale
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

Debugging the values we have:

```
> /home/user/.buildout/eggs/plone.scale-1.3.4-py2.7.egg/plone/scale/storage.py(73)scale()
     72                 import debug
---> 73                 if value['modified'] < modified - KEEP_SCALE_MILLIS:
     74                     del storage[hash]

ipdb> value['modified']
'1528896720.195449'
ipdb> modified
'1528898146.528053'
ipdb> KEEP_SCALE_MILLIS
86400000
```

How safe it's to update only plone.scale to 1.4.2 (since your fix `When getting an outdated scale, don't throw it away when there is no factory. [maurits]` is in there as well)?

**Comment by mauritsvanrees** [comment]
Plone 4.3.8 updates `plone.scale` from 1.3.5 to 1.4.1. So sounds like it should be okay to use 1.4.2.

But it also updates `plone.namedfile` from 2.0.9 to 3.0.7. Since they are related, you might want to use that one too. I am not sure if it is needed.

It updates `plone.app.upgrade` from 1.3.18 to 1.3.21, but I don't see any related stuff there, so should be fine to keep the original version.

So: it is worth a shot to update, possibly in combination with plone.namedfile.
Do it on a copy of the site of course, and confirm that it works as expected for existing images (both Archetypes and dexterity based, if relevant for your site), and for adding, editing and deleting images.

**Comment by idgserpro** [comment]
Thanks for answering @mauritsvanrees. I haven't even thought about `plone.namedfile`. Maybe it would be a good idea to check all plone.scale dependencies and do a small research.

In the worst case, a patch to this specific case can be done as well, but I want to avoid that since it gets out of control pretty quickly.

**Comment by idgserpro** [comment]
Most important changes between versions mentioned by @mauritsvanrees in https://github.com/plone/plone.scale/issues/12#issuecomment-396991237:

https://github.com/plone/plone.scale/compare/1.3.4...1.4.2#diff-d10a7080d4907760fc31685295aba766
https://github.com/plone/plone.scale/compare/1.3.4...1.4.2#diff-4e9d8caa47279e96a075975f073b3f2d

plone.scale 1.4.2 is using a new [`ScalesDict` storage](https://github.com/plone/plone.scale/compare/1.3.4...1.4.2#diff-4e9d8caa47279e96a075975f073b3f2dR152), so upgrading it's a one-way decision.

And in plone.namedfile:

https://github.com/plone/plone.namedfile/compare/2.0.9...3.0.7#diff-3191fc72b422536280e8a8692b6d23d7
https://github.com/plone/plone.namedfile/compare/2.0.9...3.0.7#diff-fd0e8893adafe918855b6e1b4b3dbfa8
https://github.com/plone/plone.namedfile/compare/2.0.9...3.0.7#diff-03f29bbadcdf640341c9061de5a07dcc
